version: "3"

services:
  db:
    image: mariadb
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      MYSQL_DATABASE: grouper
      MYSQL_USER: grouper
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: example

  ldap:
    image: jtgasper3/389ds-sample
    ports:
      - "389:389"
    
  idp:
    image: jtgasper3/shibboleth-idp-sample
    ports:
      - "4443:4443"
  
networks:
  default:
    external:
      name: internal
